import { createApp } from "vue";
import { createPinia } from "pinia";
import router from "./router";
// import "bootswatch/dist/lux/bootstrap.min.css";
import "bootswatch/dist/morph/bootstrap.min.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import App from "./App.vue";
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount("#app");
